//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Artiste { get; set; }
        public string Mappeur { get; set; }
        public string Pack { get; set; }
        public decimal Rate { get; set; }
        public decimal ScoreDP { get; set; }
        public decimal Flawless { get; set; }
        public decimal Perfect { get; set; }
        public decimal Great { get; set; }
        public decimal Good { get; set; }
        public decimal Bad { get; set; }
        public decimal Miss { get; set; }
        public decimal OK { get; set; }
        public decimal NG { get; set; }
        public string Type { get; set; }
    }
}
